export type QuizQuestion = {
  id: string;
  question: string;
  options: string[];
  answerIndex: number;
  explanation: string;
};

export const quizzes: Record<string, QuizQuestion[]> = {
  "gradient-descent": [
    {
      id: "gd-lr",
      question: "Learning rate is too high. What do you see first?",
      options: ["Loss falls smoothly", "Loss oscillates or explodes", "Gradients vanish", "Nothing changes"],
      answerIndex: 1,
      explanation: "Big steps overshoot the minimum — loss bounces or diverges. Lower LR or add scheduling.",
    },
    {
      id: "gd-batch",
      question: "Small batch size vs full batch: what is the tradeoff?",
      options: ["Small batches are exact but slow", "Small batches are noisy but fast per step", "Batch size never matters", "Full batch always overfits"],
      answerIndex: 1,
      explanation: "Stochastic estimates are noisy yet cheap, which often escapes sharp minima faster.",
    },
    {
      id: "gd-scale",
      question: "Why scale features before SGD?",
      options: ["It changes the model family", "It makes contours circular so one LR works", "It removes bias", "It guarantees convexity"],
      answerIndex: 1,
      explanation: "Unscaled features stretch the loss surface; one LR then crawls in one direction and explodes in another.",
    },
    {
      id: "gd-minima",
      question: "Gradient descent on non-convex loss guarantees…",
      options: ["Global minimum", "A stationary point, not necessarily global", "Zero loss", "No convergence"],
      answerIndex: 1,
      explanation: "GD stops where gradient ≈ 0 — could be local min or saddle. Restarts and momentum help.",
    },
  ],
  "linear-regression": [
    {
      id: "lr-assume",
      question: "Which assumption matters most for trustworthy p-values?",
      options: ["Features are scaled", "Residuals roughly normal + homoscedastic", "n_jobs=-1", "Positive coefficients"],
      answerIndex: 1,
      explanation: "Coefficient inference assumes well-behaved residuals; prediction alone is more forgiving.",
    },
    {
      id: "lr-outlier",
      question: "One extreme outlier appears. What happens to OLS line?",
      options: ["Nothing — OLS is robust", "Line tilts toward the outlier (squared loss)", "Intercept only shifts", "R² always improves"],
      answerIndex: 1,
      explanation: "Squared error punishes far points quadratically, so the line chases them. Try the sim drag test.",
    },
    {
      id: "lr-r2",
      question: "R² = 0.95 always means a great model?",
      options: ["Yes", "No — check residuals, leakage, and held-out data", "Only if intercept is zero", "Only with scaling"],
      answerIndex: 1,
      explanation: "High R² can hide leakage, overfit, or curved residuals. Plot residuals and validate out-of-sample.",
    },
    {
      id: "lr-intercept",
      question: "When is fit_intercept=False correct?",
      options: ["Always for speed", "When data is already centered or physics says zero input → zero output", "When features unscaled", "Never"],
      answerIndex: 1,
      explanation: "Forcing through origin on uncentered data biases every prediction.",
    },
  ],
  "logistic-regression": [
    {
      id: "log-c",
      question: "You lower C from 1.0 to 0.01. What happens?",
      options: ["Less regularization", "Stronger regularization, simpler boundary", "Solver switches", "Threshold auto-tunes"],
      answerIndex: 1,
      explanation: "C is inverse strength — small C shrinks weights hard toward a smoother boundary.",
    },
    {
      id: "log-converge",
      question: "ConvergenceWarning after 100 iters. First fix?",
      options: ["Drop max_iter", "Scale features and raise max_iter to 1000", "Switch to accuracy", "Remove intercept"],
      answerIndex: 1,
      explanation: "Unscaled features stall lbfgs; scaling + more iterations fixes most warnings.",
    },
    {
      id: "log-thresh",
      question: "Imbalanced fraud data (1% positive). Best first move?",
      options: ["Tune decision threshold + class_weight", "Lower C only", "Use R²", "Binarize labels"],
      answerIndex: 0,
      explanation: "0.5 threshold rarely fits imbalance — tune threshold and class weights on PR curves.",
    },
    {
      id: "log-prob",
      question: "Logistic outputs 0.8. That means…",
      options: ["80% calibrated chance if model calibrated", "Always exactly 80% true rate", "Model is overfit", "Decision is positive regardless of threshold"],
      answerIndex: 0,
      explanation: "Scores rank well but need calibration checks before reading as true probabilities.",
    },
  ],
  "polynomial-regression": [
    {
      id: "poly-degree",
      question: "Train error falls but validation error rises as degree grows. This is…",
      options: ["Underfitting", "Overfitting — added wiggle memorizes noise", "Data leakage", "Convergence"],
      answerIndex: 1,
      explanation: "Classic variance explosion. Add Ridge or drop degree.",
    },
    {
      id: "poly-guard",
      question: "Best guard when using degree ≥ 3?",
      options: ["No scaling needed", "Ridge/Lasso + StandardScaler + validation", "fit_intercept=False", "Higher batch size"],
      answerIndex: 1,
      explanation: "Polynomial features explode in scale — regularize and standardize.",
    },
    {
      id: "poly-interact",
      question: "interaction_only=True does what?",
      options: ["Keeps only cross terms, drops pure powers", "Keeps only bias", "Disables scaling", "Adds RBF kernel"],
      answerIndex: 0,
      explanation: "Useful to curb feature count while keeping interactions.",
    },
    {
      id: "poly-degree-cap",
      question: "Sane default degree to try first?",
      options: ["10", "2–3 with validation", "0", "100"],
      answerIndex: 1,
      explanation: "Start simple, let validation justify wiggle.",
    },
  ],
  svr: [
    {
      id: "svr-eps",
      question: "You widen epsilon. What happens?",
      options: ["More support vectors, tighter fit", "Fewer support vectors, flatter fit inside wider tube", "Kernel switches", "C ignored"],
      answerIndex: 1,
      explanation: "Points inside the tube cost nothing — wider tube tolerates more deviation.",
    },
    {
      id: "svr-c",
      question: "Huge C on noisy data gives…",
      options: ["Smoother model", "Overfit — bends to punish every violation", "Underfit", "No change"],
      answerIndex: 1,
      explanation: "C punishes outside-tube errors; too high memorizes noise.",
    },
    {
      id: "svr-scale",
      question: "Why is scaling mandatory for SVR?",
      options: ["For p-values", "Kernel distances and epsilon assume comparable scales", "For intercept", "It isn't"],
      answerIndex: 1,
      explanation: "Unscaled features distort rbf distances and the tube width.",
    },
    {
      id: "svr-gamma",
      question: "Very high gamma on RBF kernel…",
      options: ["Spiky island-like fit around points", "Linear fit", "Wider tube", "Fewer vectors always"],
      answerIndex: 0,
      explanation: "Each point influences only a tiny radius — memorizes.",
    },
  ],
  "decision-trees": [
    {
      id: "dt-depth",
      question: "First knob to stop an overfit tree?",
      options: ["criterion", "max_depth", "random_state", "verbose"],
      answerIndex: 1,
      explanation: "Cap depth to 3–8, then tune min_samples_split and ccp_alpha.",
    },
    {
      id: "dt-impurity",
      question: "Gini vs entropy — practical difference?",
      options: ["Huge accuracy gap", "Usually tiny; gini is faster", "Entropy never works", "Gini needs scaling"],
      answerIndex: 1,
      explanation: "Splits differ slightly; depth and pruning dominate.",
    },
    {
      id: "dt-prune",
      question: "ccp_alpha > 0 does what?",
      options: ["Grows deeper tree", "Prunes weak subtrees that don't pay impurity cost", "Scales features", "Balances classes"],
      answerIndex: 1,
      explanation: "Cost-complexity pruning removes noise branches.",
    },
    {
      id: "dt-split",
      question: "min_samples_split=20 vs 2 gives…",
      options: ["Deeper, noisier tree", "Smoother, shallower splits", "No effect", "Linear model"],
      answerIndex: 1,
      explanation: "Requiring more samples per split regularizes greedily.",
    },
  ],
  "k-nearest-neighbors": [
    {
      id: "knn-k",
      question: "k=1 on noisy labels gives…",
      options: ["Smooth boundary", "Jagged overfit boundary", "Linear boundary", "No boundary"],
      answerIndex: 1,
      explanation: "Single-neighbor vote memorizes every noisy point.",
    },
    {
      id: "knn-scale",
      question: "Feature A spans 0–1000, B spans 0–1. Without scaling…",
      options: ["Both matter equally", "A dominates distances, B ignored", "B dominates", "KNN auto-scales"],
      answerIndex: 1,
      explanation: "Euclidean distance is scale-sensitive — always standardize.",
    },
    {
      id: "knn-weights",
      question: "weights='distance' helps when…",
      options: ["Classes overlap heavily", "Dense clusters where close votes should count more", "k is huge", "Data is text"],
      answerIndex: 1,
      explanation: "Inverse-distance weighting trusts near neighbors most.",
    },
    {
      id: "knn-speed",
      question: "KNN predict cost grows with…",
      options: ["k only", "Training set size (stores all points)", "max_iter", "epsilon"],
      answerIndex: 1,
      explanation: "Lazy learner — prediction scans stored data. Slow on big sets.",
    },
  ],
  "naive-bayes": [
    {
      id: "nb-assume",
      question: "'Naive' assumption is…",
      options: ["Gaussian data", "Features independent given class", "Balanced classes", "Linear boundary"],
      answerIndex: 1,
      explanation: "Wrong but useful — works well for text despite correlated words.",
    },
    {
      id: "nb-alpha",
      question: "Unseen word at test time with alpha=0 gives…",
      options: ["Smoothed estimate", "Zero probability wipes out the class", "Ignored safely", "Higher accuracy"],
      answerIndex: 1,
      explanation: "Additive smoothing (alpha>0) prevents zero-product collapse.",
    },
    {
      id: "nb-variant",
      question: "TF-IDF text counts pair with…",
      options: ["GaussianNB", "MultinomialNB", "BernoulliNB always", "KNN"],
      answerIndex: 1,
      explanation: "Multinomial models count/frequency features; Gaussian is for continuous.",
    },
    {
      id: "nb-prior",
      question: "fit_prior=False + no class_prior means…",
      options: ["Learned priors", "Uniform priors assumed", "Error", "Balanced accuracy"],
      answerIndex: 1,
      explanation: "Useful when deployment balance differs from train.",
    },
  ],
  "kernel-trick": [
    {
      id: "kt-why",
      question: "Kernel trick lets us…",
      options: ["Avoid all math", "Separate in high-D without computing coordinates explicitly", "Skip scaling", "Guarantee convexity"],
      answerIndex: 1,
      explanation: "Kernels compute inner products in lifted space implicitly.",
    },
    {
      id: "kt-rbf",
      question: "RBF kernel gamma controls…",
      options: ["Tube width", "Influence radius of one point", "Tree depth", "Learning rate"],
      answerIndex: 1,
      explanation: "Same intuition as SVR gamma — high means spiky.",
    },
    {
      id: "kt-linear",
      question: "When is linear kernel enough?",
      options: ["Always", "When data already separable / features rich", "For images only", "Never"],
      answerIndex: 1,
      explanation: "Start linear; lift only if boundary curves.",
    },
    {
      id: "kt-scale",
      question: "Kernels and scaling…",
      options: ["Unrelated", "RBF distances need scaled features", "Only trees need it", "Scaling hurts kernels"],
      answerIndex: 1,
      explanation: "Distance-based kernels inherit KNN/SVR scale sensitivity.",
    },
  ],
  "least-squares": [
    {
      id: "ls-loss",
      question: "OLS minimizes…",
      options: ["Absolute errors", "Sum of squared residuals", "Max error", "Hinge loss"],
      answerIndex: 1,
      explanation: "Squared loss yields closed-form normal equations but chases outliers.",
    },
    {
      id: "ls-solution",
      question: "Closed-form OLS solution needs…",
      options: ["Gradient loop only", "Invertible XᵀX (no perfect collinearity)", "Scaling", "Kernel"],
      answerIndex: 1,
      explanation: "Duplicate/collinear features break the inverse — drop or regularize.",
    },
    {
      id: "ls-outlier2",
      question: "Robust alternative to squared loss?",
      options: ["Huber / MAE", "Higher degree", "Lower C", "More depth"],
      answerIndex: 0,
      explanation: "Huber blends squared + absolute to resist outliers.",
    },
    {
      id: "ls-intercept2",
      question: "OLS intercept captures…",
      options: ["Slope", "Mean offset when features are zero", "Noise", "Regularization"],
      answerIndex: 1,
      explanation: "Center features to interpret slope cleanly.",
    },
  ],
  "what-is-ml": [
    {
      id: "ml-model",
      question: "A model is…",
      options: ["The dataset", "A function mapping inputs to predicted answer shape", "An API key", "A plot"],
      answerIndex: 1,
      explanation: "Regression outputs numbers, classification outputs labels, LLMs output tokens.",
    },
    {
      id: "ml-split",
      question: "Regression vs classification differs by…",
      options: ["Data size", "Answer shape: number vs label", "Language", "Speed"],
      answerIndex: 1,
      explanation: "Same pipeline, different target and metrics.",
    },
    {
      id: "ml-dl",
      question: "Reach for deep learning when…",
      options: ["Tiny tabular data", "Unstructured data (image/text) at scale", "Always first", "Never"],
      answerIndex: 1,
      explanation: "Trees/linear win small tabular; nets win perceptual scale.",
    },
    {
      id: "ml-loop",
      question: "Beginner loop order?",
      options: ["Deploy then collect", "Baseline → error analysis → iterate", "Tune hyperparameters first", "Label test set daily"],
      answerIndex: 1,
      explanation: "Simple baseline + error slices beats blind tuning.",
    },
  ],
  "first-project": [
    {
      id: "fp-venv",
      question: "Why venv first?",
      options: ["Speed", "Reproducible deps isolated per project", "Accuracy boost", "GPU access"],
      answerIndex: 1,
      explanation: "Pin pandas/sklearn/fastapi per project, avoid global clashes.",
    },
    {
      id: "fp-split",
      question: "Split before or after preprocessing fit?",
      options: ["Fit on all data then split", "Split first, fit preprocessing on train only", "No split needed", "Split test only"],
      answerIndex: 1,
      explanation: "Fitting scalers on test leaks statistics.",
    },
    {
      id: "fp-api",
      question: "FastAPI + Pydantic gives…",
      options: ["Higher accuracy", "Validated typed prediction endpoint", "Free GPU", "Auto labels"],
      answerIndex: 1,
      explanation: "Schema validation catches bad payloads before model runs.",
    },
    {
      id: "fp-metric",
      question: "Imbalanced classes — report…",
      options: ["Accuracy only", "Precision/recall + PR curve", "R²", "Loss only"],
      answerIndex: 1,
      explanation: "Accuracy lies when 99% is one class.",
    },
  ],
  "good-vs-bad-models": [
    {
      id: "gb-under",
      question: "High bias (underfit) shows as…",
      options: ["Train and validation both poor", "Train perfect, validation poor", "Both perfect", "Random"],
      answerIndex: 0,
      explanation: "Too simple to capture signal — add capacity/features.",
    },
    {
      id: "gb-over",
      question: "Overfit signature?",
      options: ["Both poor", "Train great, validation gap large", "Both great", "Flat loss"],
      answerIndex: 1,
      explanation: "Memorized train; regularize, get data, or simplify.",
    },
    {
      id: "gb-reg",
      question: "L1 vs L2?",
      options: ["Same", "L1 sparsifies (selects), L2 shrinks smoothly", "L1 smooths only", "Neither helps"],
      answerIndex: 1,
      explanation: "Lasso zeroes weak features; Ridge keeps all small.",
    },
    {
      id: "gb-val",
      question: "Why separate validation from test?",
      options: ["Tradition", "Tuning on test leaks; validation guides, test judges once", "Speed", "No reason"],
      answerIndex: 1,
      explanation: "Touch test once at the end or scores inflate.",
    },
  ],
};
