export type QuizQuestion = {
  id: string;
  question: string;
  options: string[];
  answerIndex: number;
  explanation: string;
};

export const quizzes: Record<string, QuizQuestion[]> = {
  "gradient-descent": [
    {
      id: "gd-lr",
      question: "Learning rate is too high. What do you see first?",
      options: ["Loss diverges or oscillates", "Loss falls smoothly to zero", "Gradients vanish entirely", "Loss stays exactly flat"],
      answerIndex: 0,
      explanation: "Big steps overshoot the minimum — loss bounces or diverges. Lower LR or add scheduling.",
    },
    {
      id: "gd-batch",
      question: "Small batch size vs full batch: what is the tradeoff?",
      options: ["Exact but slow full-batch steps", "Noisy but fast small-batch steps", "Batch size changes nothing", "Full batches always overfit"],
      answerIndex: 1,
      explanation: "Stochastic estimates are noisy yet cheap, which often escapes sharp minima faster.",
    },
    {
      id: "gd-scale",
      question: "Why scale features before SGD?",
      options: ["It changes the model family", "It removes the bias term", "It makes one learning rate work", "It guarantees convexity"],
      answerIndex: 2,
      explanation: "Unscaled features stretch the loss surface; one LR then crawls in one direction and explodes in another.",
    },
    {
      id: "gd-minima",
      question: "Gradient descent on non-convex loss guarantees…",
      options: ["The global minimum", "Exactly zero training loss", "It never converges at all", "A local stationary point"],
      answerIndex: 3,
      explanation: "GD stops where gradient ≈ 0 — could be local min or saddle. Restarts and momentum help.",
    },
  ],
  "linear-regression": [
    {
      id: "lr-assume",
      question: "Which assumption matters most for trustworthy p-values?",
      options: ["Features are standardized", "Residuals normal, spread even", "n_jobs is set to minus one", "All coefficients stay positive"],
      answerIndex: 1,
      explanation: "Coefficient inference assumes well-behaved residuals; prediction alone is more forgiving.",
    },
    {
      id: "lr-outlier",
      question: "One extreme outlier appears. What happens to OLS line?",
      options: ["Nothing changes — OLS is robust", "Only the intercept shifts over", "Line tilts toward the outlier", "R² always improves a lot"],
      answerIndex: 2,
      explanation: "Squared error punishes far points quadratically, so the line chases them. Try the sim drag test.",
    },
    {
      id: "lr-r2",
      question: "R² = 0.95 always means a great model?",
      options: ["Yes, in every single case", "Only with a zero intercept", "Only on scaled-up features", "No — validate out-of-sample"],
      answerIndex: 3,
      explanation: "High R² can hide leakage, overfit, or curved residuals. Plot residuals and validate out-of-sample.",
    },
    {
      id: "lr-intercept",
      question: "When is fit_intercept=False correct?",
      options: ["When data is already centered", "Always, for extra speed gains", "When features stay unscaled", "Never, always keep it on"],
      answerIndex: 0,
      explanation: "Forcing through origin on uncentered data biases every prediction.",
    },
  ],
  "logistic-regression": [
    {
      id: "log-c",
      question: "You lower C from 1.0 to 0.01. What happens?",
      options: ["Regularization gets weaker", "The solver switches methods", "Regularization gets stronger", "Threshold auto-tunes itself"],
      answerIndex: 2,
      explanation: "C is inverse strength — small C shrinks weights hard toward a smoother boundary.",
    },
    {
      id: "log-converge",
      question: "ConvergenceWarning after 100 iters. First fix?",
      options: ["Lower max_iter further down", "Switch to plain accuracy", "Remove the intercept term", "Scale features, raise max_iter"],
      answerIndex: 3,
      explanation: "Unscaled features stall lbfgs; scaling + more iterations fixes most warnings.",
    },
    {
      id: "log-thresh",
      question: "Imbalanced fraud data (1% positive). Best first move?",
      options: ["Tune threshold + class_weight", "Just lower C and hope for best", "Report R² and move along", "Binarize all of the labels"],
      answerIndex: 0,
      explanation: "0.5 threshold rarely fits imbalance — tune threshold and class weights on PR curves.",
    },
    {
      id: "log-prob",
      question: "Logistic outputs 0.8. That means…",
      options: ["Always exactly 80% true rate", "About 80% chance if calibrated", "Proof the model has overfit", "Positive at any threshold used"],
      answerIndex: 1,
      explanation: "Scores rank well but need calibration checks before reading as true probabilities.",
    },
  ],
  "polynomial-regression": [
    {
      id: "poly-degree",
      question: "Train error falls but validation error rises as degree grows. This is…",
      options: ["Mere underfitting instead", "Pure data leakage here", "Slow convergence issues", "Overfit from extra wiggle"],
      answerIndex: 3,
      explanation: "Classic variance explosion. Add Ridge or drop degree.",
    },
    {
      id: "poly-guard",
      question: "Best guard when using degree ≥ 3?",
      options: ["Ridge, scaling, and validation", "No scaling is ever needed", "Set fit_intercept to False", "Raise the batch size a lot"],
      answerIndex: 0,
      explanation: "Polynomial features explode in scale — regularize and standardize.",
    },
    {
      id: "poly-interact",
      question: "interaction_only=True does what?",
      options: ["Keeps only the bias term", "Cross terms only, no powers", "Disables feature scaling", "Adds an RBF kernel mapping"],
      answerIndex: 1,
      explanation: "Useful to curb feature count while keeping interactions.",
    },
    {
      id: "poly-degree-cap",
      question: "Sane default degree to try first?",
      options: ["10 is the safest choice", "0 avoids all overfitting", "Try 2–3 with validation", "100 for the most power"],
      answerIndex: 2,
      explanation: "Start simple, let validation justify wiggle.",
    },
  ],
  svr: [
    {
      id: "svr-eps",
      question: "You widen epsilon. What happens?",
      options: ["Wider tube, flatter fit inside", "More vectors and tighter fit", "The kernel switches over", "C gets fully ignored now"],
      answerIndex: 0,
      explanation: "Points inside the tube cost nothing — wider tube tolerates more deviation.",
    },
    {
      id: "svr-c",
      question: "Huge C on noisy data gives…",
      options: ["A much smoother model", "Overfit that bends to noise", "A clean underfit instead", "No real change at all"],
      answerIndex: 1,
      explanation: "C punishes outside-tube errors; too high memorizes noise.",
    },
    {
      id: "svr-scale",
      question: "Why is scaling mandatory for SVR?",
      options: ["To get valid p-values out", "To fit the intercept term", "So kernels see equal scales", "Scaling is never needed"],
      answerIndex: 2,
      explanation: "Unscaled features distort rbf distances and the tube width.",
    },
    {
      id: "svr-gamma",
      question: "Very high gamma on RBF kernel…",
      options: ["An almost linear fit", "A much wider tube used", "Fewer vectors, always", "Spiky fits around points"],
      answerIndex: 3,
      explanation: "Each point influences only a tiny radius — memorizes.",
    },
  ],
  "decision-trees": [
    {
      id: "dt-depth",
      question: "First knob to stop an overfit tree?",
      options: ["The split criterion", "A cap on max_depth", "The random_state seed", "Verbose logging on"],
      answerIndex: 1,
      explanation: "Cap depth to 3–8, then tune min_samples_split and ccp_alpha.",
    },
    {
      id: "dt-impurity",
      question: "Gini vs entropy — practical difference?",
      options: ["A huge accuracy gap", "Entropy never converges", "Tiny gap; gini is faster", "Gini needs scaled inputs"],
      answerIndex: 2,
      explanation: "Splits differ slightly; depth and pruning dominate.",
    },
    {
      id: "dt-split",
      question: "min_samples_split=20 vs 2 gives…",
      options: ["Deeper and noisier splits", "It has zero real effect", "A purely linear model", "Smoother shallow splits"],
      answerIndex: 3,
      explanation: "Requiring more samples per split regularizes greedily.",
    },
    {
      id: "dt-prune",
      question: "ccp_alpha > 0 does what?",
      options: ["Prunes weak, costly branches", "Grows the tree even deeper", "Scales all of the features", "Balances the class weights"],
      answerIndex: 0,
      explanation: "Cost-complexity pruning removes noise branches.",
    },
  ],
  "k-nearest-neighbors": [
    {
      id: "knn-k",
      question: "k=1 on noisy labels gives…",
      options: ["A smooth, even boundary", "A straight linear split", "Jagged overfit boundary", "No boundary forms at all"],
      answerIndex: 2,
      explanation: "Single-neighbor vote memorizes every noisy point.",
    },
    {
      id: "knn-scale",
      question: "Feature A spans 0–1000, B spans 0–1. Without scaling…",
      options: ["Both count the same", "B takes over instead", "KNN scales by itself", "A swamps B in distances"],
      answerIndex: 3,
      explanation: "Euclidean distance is scale-sensitive — always standardize.",
    },
    {
      id: "knn-weights",
      question: "weights='distance' helps when…",
      options: ["Where close votes count more", "Where classes overlap a lot", "When k gets very huge", "On raw text features"],
      answerIndex: 0,
      explanation: "Inverse-distance weighting trusts near neighbors most.",
    },
    {
      id: "knn-speed",
      question: "KNN predict cost grows with…",
      options: ["Only when k gets larger", "Grows with training size", "With higher max_iter", "With a larger epsilon"],
      answerIndex: 1,
      explanation: "Lazy learner — prediction scans stored data. Slow on big sets.",
    },
  ],
  "naive-bayes": [
    {
      id: "nb-assume",
      question: "'Naive' assumption is…",
      options: ["Strictly Gaussian-only data", "Perfectly balanced classes", "Always a linear boundary", "Features independent per class"],
      answerIndex: 3,
      explanation: "Wrong but useful — works well for text despite correlated words.",
    },
    {
      id: "nb-alpha",
      question: "Unseen word at test time with alpha=0 gives…",
      options: ["Zeroes wipe out the class", "A nicely smoothed estimate", "Safely ignored by the model", "Even higher accuracy scores"],
      answerIndex: 0,
      explanation: "Additive smoothing (alpha>0) prevents zero-product collapse.",
    },
    {
      id: "nb-variant",
      question: "TF-IDF text counts pair with…",
      options: ["Plain GaussianNB instead", "MultinomialNB for counts", "Always BernoulliNB", "Use KNN on the text"],
      answerIndex: 1,
      explanation: "Multinomial models count/frequency features; Gaussian is for continuous.",
    },
    {
      id: "nb-prior",
      question: "fit_prior=False + no class_prior means…",
      options: ["Priors learned from data", "A hard error is raised", "Uniform priors are assumed", "Balanced accuracy metric"],
      answerIndex: 2,
      explanation: "Useful when deployment balance differs from train.",
    },
  ],
  "kernel-trick": [
    {
      id: "kt-why",
      question: "Kernel trick lets us…",
      options: ["Separate without coordinates", "Skip all of the math", "Skip every scaling step", "Guarantee full convexity"],
      answerIndex: 0,
      explanation: "Kernels compute inner products in lifted space implicitly.",
    },
    {
      id: "kt-rbf",
      question: "RBF kernel gamma controls…",
      options: ["The epsilon tube width", "How far one point reaches", "The maximum tree depth", "The base learning rate"],
      answerIndex: 1,
      explanation: "Same intuition as SVR gamma — high means spiky.",
    },
    {
      id: "kt-linear",
      question: "When is linear kernel enough?",
      options: ["Always the best pick", "Only for image inputs", "When data is separable", "Never the right call"],
      answerIndex: 2,
      explanation: "Start linear; lift only if boundary curves.",
    },
    {
      id: "kt-scale",
      question: "Kernels and scaling…",
      options: ["They are unrelated", "Only trees need scaling", "Scaling damages kernels", "RBF needs scaled inputs"],
      answerIndex: 3,
      explanation: "Distance-based kernels inherit KNN/SVR scale sensitivity.",
    },
  ],
  "least-squares": [
    {
      id: "ls-loss",
      question: "OLS minimizes…",
      options: ["Absolute errors summed", "Sum of squared residuals", "The single max error", "Hinge loss instead"],
      answerIndex: 1,
      explanation: "Squared loss yields closed-form normal equations but chases outliers.",
    },
    {
      id: "ls-solution",
      question: "Closed-form OLS solution needs…",
      options: ["Only a gradient descent loop", "Scaled features beforehand", "An invertible XᵀX matrix", "A kernel trick applied"],
      answerIndex: 2,
      explanation: "Duplicate/collinear features break the inverse — drop or regularize.",
    },
    {
      id: "ls-outlier2",
      question: "Robust alternative to squared loss?",
      options: ["Higher polynomial degree", "A much lower C value", "Growing much deeper trees", "Huber or MAE loss instead"],
      answerIndex: 3,
      explanation: "Huber blends squared + absolute to resist outliers.",
    },
    {
      id: "ls-intercept2",
      question: "OLS intercept captures…",
      options: ["Mean offset at zero features", "The slope of the line", "Pure random noise here", "Regularization amount set"],
      answerIndex: 0,
      explanation: "Center features to interpret slope cleanly.",
    },
  ],
  "what-is-ml": [
    {
      id: "ml-model",
      question: "A model is…",
      options: ["The raw dataset", "An API key string", "Input-to-answer function", "A static chart or plot"],
      answerIndex: 2,
      explanation: "Regression outputs numbers, classification outputs labels, LLMs output tokens.",
    },
    {
      id: "ml-split",
      question: "Regression vs classification differs by…",
      options: ["How big the data is", "Which language you use", "How fast training runs", "Numbers vs labels output"],
      answerIndex: 3,
      explanation: "Same pipeline, different target and metrics.",
    },
    {
      id: "ml-dl",
      question: "Reach for deep learning when…",
      options: ["Unstructured data at scale", "Tiny tabular datasets", "Always as a first attempt", "Never a good idea here"],
      answerIndex: 0,
      explanation: "Trees/linear win small tabular; nets win perceptual scale.",
    },
    {
      id: "ml-loop",
      question: "Beginner loop order?",
      options: ["Deploy, then collect data", "Baseline, errors, then iterate", "Tune hyperparameters first", "Label the test set daily"],
      answerIndex: 1,
      explanation: "Simple baseline + error slices beats blind tuning.",
    },
  ],
  "first-project": [
    {
      id: "fp-venv",
      question: "Why venv first?",
      options: ["Faster installs here", "Higher model accuracy", "Direct GPU access here", "Per-project isolated deps"],
      answerIndex: 3,
      explanation: "Pin pandas/sklearn/fastapi per project, avoid global clashes.",
    },
    {
      id: "fp-split",
      question: "Split before or after preprocessing fit?",
      options: ["Split first, fit only on train", "Fit on everything, then split", "Skip splitting entirely", "Only split the test set"],
      answerIndex: 0,
      explanation: "Fitting scalers on test leaks statistics.",
    },
    {
      id: "fp-api",
      question: "FastAPI + Pydantic gives…",
      options: ["Slightly higher accuracy", "A typed prediction endpoint", "Some free GPU minutes", "Auto-labeled datasets"],
      answerIndex: 1,
      explanation: "Schema validation catches bad payloads before model runs.",
    },
    {
      id: "fp-metric",
      question: "Imbalanced classes — report…",
      options: ["Accuracy alone suffices", "R² on the test split", "Precision/recall, PR curve", "Training loss alone"],
      answerIndex: 2,
      explanation: "Accuracy lies when 99% is one class.",
    },
  ],
  "good-vs-bad-models": [
    {
      id: "gb-under",
      question: "High bias (underfit) shows as…",
      options: ["Both train and validation poor", "Train perfect, test is poor", "Everything looks perfect", "Purely random behavior"],
      answerIndex: 0,
      explanation: "Too simple to capture signal — add capacity/features.",
    },
    {
      id: "gb-over",
      question: "Overfit signature?",
      options: ["Both sets look poor", "Train/val gap: memorized", "Both sets look great", "Loss stays totally flat"],
      answerIndex: 1,
      explanation: "Memorized train; regularize, get data, or simplify.",
    },
    {
      id: "gb-reg",
      question: "L1 vs L2?",
      options: ["L1 and L2 are the same", "Only L1 smooths weights", "L1 selects, L2 shrinks", "Neither ever helps"],
      answerIndex: 2,
      explanation: "Lasso zeroes weak features; Ridge keeps all small.",
    },
    {
      id: "gb-val",
      question: "Why separate validation from test?",
      options: ["Mere tradition", "Faster training runs", "No real reason at all", "Val tunes, test judges"],
      answerIndex: 3,
      explanation: "Touch test once at the end or scores inflate.",
    },
  ],
};
